### ISSUE TITLE
Updating feeds server port

### ISSUE THREAD

**Issue by dindoliboon** [CommunityHoneyNetwork/dionaea#13]
Hi,

When updating FEEDS_SERVER_PORT in dionaea/dionaea.sysconfig to a different port number, Dionaea will continue to use the default port 10000.

I was able to change ports after adding the following to /etc/runit/runsvdir/default/dionaea/run:
```sh
sed -i "s/port:.*/port: ${FEEDS_SERVER_PORT}/g" /opt/dionaea/etc/dionaea/ihandlers-available/hpfeeds.yaml
```

Thanks!

**Comment by JesseBowling** [comment]
Hi Dindo,

Thank you for reporting this! We'll definitely take a look at what it will take to have this option respected.

Stay tuned for a fix!

**Comment by JesseBowling** [comment]
This has been merged into master and will be in the next tagged release! Thanks @dindoliboon !
