### ISSUE TITLE
Update dionaea to version 0.8.0

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/dionaea#15]
New code here:

https://github.com/DinoTools/dionaea/tree/0.8.0

**Comment by amerck** [comment]
Dionaea currently has a bug that prevents it from dropping privileges and also open low ports. Waiting for a fix before upgrading to 0.8.0.

**Comment by JesseBowling** [comment]
Perhaps we can use authbind to allow what we need @amerck ?
